FROM node:8.16.1-alpine
WORKDIR C:\Users\Dell\Desktop\My Learnings\AWS\ECS\Docker,Devops,Master Class\node-login-master\node-login-master
COPY . C:\Users\Dell\Desktop\My Learnings\AWS\ECS\Docker,Devops,Master Class\node-login-master\node-login-master
RUN npm install
EXPOSE 5000
CMD node login.js

#ENTRYPOINT ["node", "index.js"]
#COPY package.json /app
